infrastructure: ^3
php_settings:
  version: 8.1
  cli:
    max_execution_time: 0
shared_dirs:
  mysite:
    # persist the following directories between deployments
    data: {}
    public/3: {}
    public/4: {}
    public/5: {}
    public/6: {}
    public/7: {}
    public/8: {}
    public/9: {}
crons:
  queuedjobs_task:
    time: '* * * * *'
    sake_once: "dev/tasks/ProcessJobQueueTask"
    vhost: "mysite"
url_rules:
  mysite:
    - '^.*': 'apache'
