infrastructure: ^3
php_settings:
  version: 8.1
  cli:
    max_execution_time: 0
shared_dirs:
  mysite:
    # persist the following directories between deployments
    # the static dir lives in the public dir, though do not need to specify "public/static" here
    static: {}
crons:
  queuedjobs_task:
    time: '* * * * *'
    sake_once: "dev/tasks/ProcessJobQueueTask"
    vhost: "mysite"
url_rules:
  mysite:
    - '^.*': 'apache'
