[build]
  publish = "htdocs/"
  command = "./makedoc.sh"
  functions = "./_functions"

[[redirects]]
  from = "/"
  to = "/4/"
  status = 302
  force = true
[[redirects]]
  from = "/search/lookup"
  query = {q = ":q", version = ":version"}
  to = "/.netlify/functions/lookup?q=:q&version=:version"
  status = 302
[[redirects]]
  from = "/search/lookup"
  query = {q = ":q"}
  to = "/.netlify/functions/lookup?q=:q"
  status = 302
