name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  # Every Monday at 2:20pm UTC
  schedule:
    - cron: '20 14 * * 1'

jobs:
  ci:
    name: CI
    # - Only run cron on the silverstripe account
    # - Do not run if this is a pull-request from same repo i.e. not a fork repo
    if: ((github.event_name == 'schedule' && github.repository_owner == 'silverstripe') || github.event_name != 'schedule') && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository)
    uses: silverstripe/gha-ci/.github/workflows/ci.yml@v1
